# Generated by Django 2.2.4 on 2019-09-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0024_rename_short_name_to_code")]

    operations = [
        migrations.RenameModel(old_name="GareaCategory", new_name="Layer"),
        migrations.AlterModelOptions(name="layer", options={"ordering": ("descr",)}),
        migrations.RenameField(
            model_name="garea", old_name="category", new_name="layer"
        ),
    ]
