# Generated by Django 2.2.4 on 2019-09-25 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris", "0025_rename_garea_category_to_layer")]

    operations = [
        migrations.CreateModel(
            name="LayerGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, null=True
                    ),
                ),
                ("descr", models.CharField(blank=True, max_length=200)),
            ],
            options={"ordering": ("descr",), "abstract": False},
        ),
        migrations.AlterModelOptions(
            name="layer", options={"ordering": ("group", "order")}
        ),
        migrations.AddField(
            model_name="layer",
            name="order",
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="layer",
            name="group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="enhydris.LayerGroup",
            ),
            preserve_default=False,
        ),
    ]
