# Generated by Django 2.2.12 on 2020-06-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0036_remove_timeseries_datafile_and_bounding_dates"),
    ]

    operations = [
        migrations.RenameModel(old_name="Variable", new_name="VariableType",),
        migrations.RenameModel(
            old_name="VariableTranslation", new_name="VariableTypeTranslation",
        ),
        migrations.AlterModelOptions(
            name="variabletypetranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "variable type Translation",
            },
        ),
        migrations.RenameField(
            model_name="timeseries", old_name="variable", new_name="variable_type",
        ),
        migrations.RenameField(
            model_name="unitofmeasurement",
            old_name="variables",
            new_name="variable_types",
        ),
        migrations.AlterModelTable(
            name="variabletypetranslation", table="enhydris_variabletype_translation",
        ),
    ]
