# Generated by Django 5.2.4 on 2025-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris", "0118_aggregate_and_synoptic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeseries",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (100, "Initial"),
                    (150, "Converted"),
                    (200, "Checked"),
                    (300, "Regularized"),
                    (400, "Aggregated"),
                ],
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", 150)),
                fields=("timeseries_group",),
                name="only_one_converted_timeseries_per_group",
            ),
        ),
    ]
