name: Run tests automatically

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Node 
      uses: actions/setup-node@v3
      with:
        node-version: '10'
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Install Dependencies
      run: |
        add-apt-repository -y ppa:timescale/timescaledb-ppa
        apt-get update
        apt-get install -y postgresql gdal-bin libgdal-dev postgresql-10-postgis-2.4 timescaledb-postgresql-10
        bash -c "echo \"shared_preload_libraries = 'timescaledb'\" >>/etc/postgresql/10/main/postgresql.conf"
        service postgresql restart
        python -m pip install --upgrade pip
        CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal==2.2.3'
        pip install psycopg2==2.7.4 codecov coverage isort flake8 black
        wget -O chromedriver_version https://chromedriver.storage.googleapis.com/LATEST_RELEASE_`google-chrome --version|awk '{ print $3 }'|awk -F. '{ print $1 }'`
        wget https://chromedriver.storage.googleapis.com/`cat chromedriver_version`/chromedriver_linux64.zip
        sudo unzip chromedriver_linux64.zip -d /usr/local/bin
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        nvm install 10
        npm install
        psql -U postgres -c "create extension postgis"
        psql -U postgres -c "create database openmeteo"
        cp enhydris_project/settings/travis.py enhydris_project/settings/local.py
    - name: Run Tests
      run: |
        python manage.py makemigrations --check
        black --check .
        flake8 --max-line-length=88 .
        isort --check-only --diff .
        npm run lint
        coverage run --include="./*" --omit="*/tests/*","*/tests.py","*/migrations/*","./enhydris_project/*" manage.py test -v2
        npm run test
        codecov
